name: Reuse

on:
  workflow_call:
    inputs:
      who:
        required: false
        type: string
        default: "unknown"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  job1:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: run job 1
        run: |
          echo "JOB 1: input- ${{ secrets.pass }}"
  job2:
    needs: job1
    runs-on: ubuntu-latest
    steps:
      - name: run job 2
        run: |
          echo "JOB 2: input- ${{ inputs.who }}"
  job3:
    runs-on: ubuntu-latest
    steps:
      - name: run job 3
        run: |
          echo "JOB 3 STEP: var- ${{ vars.user }}"
