name: TEST

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  j1:
    runs-on: ubuntu-latest
    steps:
      - name: vars
        run: |
          echo "> ${{ vars.user }}"
      
      - name: secrets
        run: |
          echo "> ${{ secrets.pass }}"
